Updated node, talib, tulind versions
mark-sch/GreenGekko pull request #5
Opened 2020-11-17 02:57 UTC by mcsgroi

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Updated node, talib, tulind versions.

* **What is the current behavior?** (You can also link to an open issue here)
Doesn't launch node server currently.

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

2020-11-17 23:13 UTC, mark-sch commented
Hi, thanks, you updated talib, tulind and node to latest version, did you test to use these libs with node v10? This is the preferred, tested node version right now. Updating to the latest v15 node version will at least have the impact of heavy testing and I fear not all will run out of the box.

2020-11-17 23:38 UTC, mcsgroi commented
Hello,
I wasn't sure what the preferred testing approach for this was. Everything
appeared to launch as expected although I'm new to this project. Figured
since I had the change locally I'd push it up in case you were interested
in merging it. I also won't be offended if you want to close this PR.



On Tue, Nov 17, 2020, 5:13 PM Mark Sch. <notifications@github.com> wrote:

> Hi, thanks, you updated talib, tulind and node to latest version, did you
> test to use these libs with node v10? This is the preferred, tested node
> version right now. Updating to the latest v15 node version will at least
> have the impact of heavy testing and I fear not all will run out of the box.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mark-sch/GreenGekko/pull/5#issuecomment-729270609>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACECAVD5VM557ENJONZZY6DSQL7SPANCNFSM4TX7S5OA>
> .
>

2020-12-04 18:19 UTC, XL-Reaper commented
Hi, I tried this commit and some things break with Node 15 - for instance the exchange list stays empty.

2020-12-04 18:21 UTC, XL-Reaper requested changes
Forgot the changes - skip this comment :)

2020-12-04 18:22 UTC, XL-Reaper requested changes
Change back to Node 10 so exchange selection doesn't break

2020-12-04 18:22 UTC, XL-Reaper commented on Dockerfile
> +FROM node:15
```suggestion
FROM node:10
```

2020-12-04 18:22 UTC, XL-Reaper commented on package.json
> +    "node": ">=15.2.1"
```suggestion
    "node": ">=10.13.0"
```

2021-02-09 22:46 UTC, closed without merging